// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDTRMBk7mOmpz_inQJOUMVWAXNEAFpED0c',
    appId: '1:665658922425:web:697d5759bd020f7c1c5268',
    messagingSenderId: '665658922425',
    projectId: 'expense-tracker-b84b1',
    authDomain: 'expense-tracker-b84b1.firebaseapp.com',
    storageBucket: 'expense-tracker-b84b1.firebasestorage.app',
    measurementId: 'G-MQWKYHF4LP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkgBTex_6l_eImAG0nic4QNNdtfR1XByU',
    appId: '1:665658922425:android:732d2375ee1729b01c5268',
    messagingSenderId: '665658922425',
    projectId: 'expense-tracker-b84b1',
    storageBucket: 'expense-tracker-b84b1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJ1q8Z9FD_rTSwkFolOWVpuLfcGqjlHe8',
    appId: '1:665658922425:ios:259803db8bce25521c5268',
    messagingSenderId: '665658922425',
    projectId: 'expense-tracker-b84b1',
    storageBucket: 'expense-tracker-b84b1.firebasestorage.app',
    iosBundleId: 'com.example.expenseTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBJ1q8Z9FD_rTSwkFolOWVpuLfcGqjlHe8',
    appId: '1:665658922425:ios:259803db8bce25521c5268',
    messagingSenderId: '665658922425',
    projectId: 'expense-tracker-b84b1',
    storageBucket: 'expense-tracker-b84b1.firebasestorage.app',
    iosBundleId: 'com.example.expenseTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDTRMBk7mOmpz_inQJOUMVWAXNEAFpED0c',
    appId: '1:665658922425:web:d4bded06336bc6351c5268',
    messagingSenderId: '665658922425',
    projectId: 'expense-tracker-b84b1',
    authDomain: 'expense-tracker-b84b1.firebaseapp.com',
    storageBucket: 'expense-tracker-b84b1.firebasestorage.app',
    measurementId: 'G-LC3SYYBP73',
  );
}
